# Generated by Django 3.2.16 on 2023-10-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230921_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
